### ISSUE TITLE
Error when installing TYPO3_restler with composer

### ISSUE THREAD

**Issue by tmotyl** [AOEpeople/TYPO3_Restler#11]
If you require
"aoe/restler": "1.*"
in your project compose,json, you will get error on running composer install/update:
``
  Problem 1
    - aoe/restler 1.5.6 requires luracast/restler 3.0.0.20160315 -> no matching package found.
``

**Comment by tmotyl** [comment]
adding repository to project composer json solved the issue.
```
"repositories": [
		{ "type": "vcs", "url": "https://github.com/AOEpeople/Restler.git" },
...
```

**Comment by vdespa** [comment]
Hi @tmotyl and thank you for your report.

I have updated the documentation in order to reflect this additional step.

If you have any other problems, feel free to get in touch with us.
