### ISSUE TITLE
Compatibility to 8

### ISSUE THREAD

**Issue by psychomieze** [AOEpeople/TYPO3_Restler#12]
Hello,

sadly the extension isn't working with TYPO3 8 - are there plans to upgrade?

**Comment by vdespa** [comment]
Hello Susanne,

thank you for your request. We haven't tested it with with TYPO3 8 yet, so it would be helpful to know why it is failing.

We have no concrete plans at this point but pull requests all always welcome.

Thanks for your help!

**Comment by rastocs2** [comment]
for quick fix need change 2 files:
Scripts/restler_dispatch.php
![img1](https://cloud.githubusercontent.com/assets/5691082/25171138/14851650-24ed-11e7-88a8-6eb701f71c24.png)

and 
Classes\System\TYPO3\Loader.php
![img2](https://cloud.githubusercontent.com/assets/5691082/25171209/54b86e20-24ed-11e7-9a81-a9c7ce8559fd.png)

**Comment by dwenzel** [comment]
After applying @rastocs2 's changes I still get only `Unable to determine path to entry script.`

**Comment by rastocs2** [comment]
for me it works without problems, used restler version 1.6.9 on TYPO3 8.6 and also on 8.7
without my changes was error:
![img1](https://cloud.githubusercontent.com/assets/5691082/25659525/7acbc2ee-3008-11e7-84ba-9738166cdf0e.png)

after adding $bootstrapObj->setRequestType(TYPO3_REQUESTTYPE_FE); to Classes\System\TYPO3\Loader.php was error:
![img2](https://cloud.githubusercontent.com/assets/5691082/25659545/90ff3456-3008-11e7-84cd-6608a1d50c81.png)

after adding 
$thisScriptRelativePath = 'typo3conf/ext/restler/Scripts';
define('PATH_site', str_replace($thisScriptRelativePath, '' ,__DIR__));
to Scripts\restler_dispatch.php it works without problems
![img3](https://cloud.githubusercontent.com/assets/5691082/25659576/adf9730a-3008-11e7-8a49-3312a59fb5db.png)

**Comment by dwenzel** [comment]
OK, I'm on TYPO3 8.7.1 in Composer Mode with restler 1.6.10

The error mentiond above was caused by the invalid argument _entryPointLevel_ in 
```
$bootstrapObj->baseSetup('typo3conf/ext/restler/Scripts/');
```
When I use integer `4` instead, I get:
```
Access to undeclared static property: Luracast\Restler\Scope::$resolver

Error thrown in file
/app/web/typo3conf/ext/restler/Classes/System/Restler/Builder.php in line 181.

3 Aoe\Restler\System\Restler\Builder::setAutoLoading()

/app/web/typo3conf/ext/restler/Classes/System/Restler/Builder.php:

00079:     public function build()
00080:     {
00081:         $this->setAutoLoading();
00082:         $this->setCacheDirectory();
00083:         $this->setServerConfiguration();
2 Aoe\Restler\System\Restler\Builder::build()
[...]
```

**Comment by rastocs2** [comment]
sorry, i didn't try yet 1.6.10, when i will have a time i can check it
1.6.9 works perfect for me, i like restler extension, i only wanted help to others use it under TYPO3 8

**Comment by rastocs2** [comment]
tried version 1.6.10, it works with my changes without problems:
Scripts\restler_dispatch.php

![image](https://cloud.githubusercontent.com/assets/5691082/25985946/985cc466-36ed-11e7-88da-d38d9005696d.png)

Classes\System\TYPO3\Loader.php

![image](https://cloud.githubusercontent.com/assets/5691082/25986125/855ddff2-36ee-11e7-8c40-3bd5bba8a38d.png)

**Comment by dwenzel** [comment]
@rastocs2 did you install `restler` via composer or via Extension Manager?

**Comment by dwenzel** [comment]
I just figured out that my installation lacked two steps described in the [Installation Guide](https://docs.typo3.org/typo3cms/extensions/restler/Pages/InstallationGuide.html)

In root composer.json:
```
"require": {
        ...
        "aoe/restler": "1.*"
}
"autoload": {
        "psr-0": {
                "Luracast\\Restler\\": "vendor/luracast/restler/vendor"
        }
},
```
Anyhow - it doesn't fix the issue for me. Now I get: 

```
#1203699034: A cache with identifier "tx_restler_cache" does not exist. (More information)

TYPO3\CMS\Core\Cache\Exception\NoSuchCacheException thrown in file
/app/vendor/typo3/cms/typo3/sysext/core/Classes/Cache/CacheManager.php in line 119.

5 TYPO3\CMS\Core\Cache\CacheManager::getCache("tx_restler_cache")


/app/web/typo3conf/ext/restler/Classes/System/Restler/Builder.php:

00210:     private function getCache()
00211:     {

00212:         return $this->cacheManager->getCache('tx_restler_cache')->getBackend();

00213:     }
00214: }
```
It seem's there is less Frontend initialized than expected by the builder. 
Allthough in Backend/Configuration `tx_restler_cache` is listed it is not present when calling the API explorer script.

**Comment by rastocs2** [comment]
I installed restler via Extension Manager
