### ISSUE TITLE
ClassLoading fails

### ISSUE THREAD

**Issue by tbmph** [AOEpeople/TYPO3_Restler#16]
When I try to inject a repository I get the following error message;

`{
  "error": {
    "code": 500,
    "message": "Internal Server Error: Could not analyse class: \"TYPO3\\CMS\\Extbase\\Persistence\\PersistenceManager\" maybe not loaded or no autoloader? Class TYPO3\\CMS\\Extbase\\Persistence\\PersistenceManager does not exist"
  },
  "debug": {
    "source": "ClassInfoFactory.php:35 at call stage",
    "stages": {
      "success": [
        "get",
        "get",
        "route",
        "negotiate",
        "validate"
      ],
      "failure": [
        "call",
        "message"
      ]
    }
  }
}`

The typo3 installation I'm working on is not a composer install and points right to the typo3 dir, as the customer has no shell access, thus cannot create links.
I changed the path in System\TYPO3\Loader::getClassLoader to point to "/../../../../../../vendor/autoload.php" which allowed me to install restler ext and make it work.

Any hint what goes wrong?

I already deleted  typo3temp/autoloader and typo3temp/Cache/Code directories.
What puzzle me a is that there is no class from TYPO3\ in autoload_classmap.php - I would expect it to be there...

**Comment by srotsch** [comment]
Could you please provide details about

- which TYPO3 version you are using,
- the extension version and
- whether you install it via TER or by cloning the repository and uploading the files

Thanks!

**Comment by hoswmph** [comment]
Hi
this is the system setup:
- typo3 7.612
- php 5.5.38
- ext-version 1.6.8 via TER

Hope this helps.

**Comment by hoswmph** [comment]
Did a little try and error...

Adding 
`$bootstrapObj->loadTypo3LoadedExtAndExtLocalconf(TRUE);`
in System/TYPO3/Loader.php solves the injection problem.

Might it be it has something to do with the configuration of the extension?
Am I missing something here:
`basic.extensionsWithRequiredExtLocalConfFiles = restler,my_restler_ext_stuff`

**Comment by srotsch** [comment]
Thanks for investigating further, I think you are on the right track: please try adding "extbase" to the list of extensions in `basic.extensionsWithRequiredExtLocalConfFiles` in the extension settings or leave the field empty (for debugging purposes).
I checked the configuration we're using, and "extbase" is in the list of extension keys to load.

**Comment by hoswmph** [comment]
I can confirm adding "extbase" to `basic.extensionsWithRequiredExtLocalConfFiles` solves the problem.
This should be added to the docs of [restler_examples](https://github.com/AOEpeople/TYPO3_RestlerExamples) at least.
Thanks for helping me to pin this down!

**Comment by srotsch** [comment]
Cool! I'll close the issue then.

We will also discuss how to clarify the purpose of this particular setting and if e.g. making "extbase" a default makes sense.

**Comment by tbmph** [comment]
I would suggest adding it to the description of the setting in restler or even better and user-friendly, make it an own setting like "Use Extbase with restler".
Guess the first option would be enough for the experienced user.
