### ISSUE TITLE
typo3cache doesn’t respect defaultGetVars

### ISSUE THREAD

**Issue by saneinsane** [AOEpeople/TYPO3_Restler#21]
When setting the cache entry the defaultGetVars are going into GET vars (via TSFE->getConfigArray()) and are thus added to cache identifier.
When fetching the entry (RestApiRequest->handle()) it seems that the defaultGetVars are not respected so that the cache entry is never found.
Example: 
config.defaultGetVars.L = 1
/api/myendpoint/ doesn‘t use the cache
/api/myendpoint/?L=0 uses the cache.

**Comment by felixsemmler** [comment]
Please check the latest version of [restler](https://extensions.typo3.org/extension/restler) and [restler_examples](https://extensions.typo3.org/extension/restler_examples). We did some changes and update the code for TYPO3V10.
