### ISSUE TITLE
Local File Disclosure 

### ISSUE THREAD

**Issue by CCrashBandicot** [AOEpeople/TYPO3_Restler#25]
Hello I'Find in the last version of restler (1.7.0) for Typo3 Vulnerability in File getsource.php

Line : 

3.      $file = $_GET['file'];
13.        $text = file_get_contents($file);
16.      die($file . '<pre id="php">' . htmlspecialchars($text) . "</pre>");

This allow attacker read any file in website.

Proof : https://i.imgur.com/zObmaDD.png

on pictures i'read file LocalConfiguration.php 
LocalConfiguration.php Stores Credentials Information

.

**Comment by srotsch** [comment]
Hi @CCrashBandicot, thanks for letting us know.

On first sight, the affected file is part of some code examples shipped with the third-party restler library. We will figure out how to mitigate the issue and then release a new version.

Thanks again!

**Comment by tmotyl** [comment]
usually vendor folder is outside of the document root.
Can you tell what is the full url  you've tried - the screenshot doesnt contain the beginning of the url

**Comment by srotsch** [comment]
Hej @tmotyl thanks for providing a fix that quick :-)

I felt free to cherry-pick it to the AOEpeople fork of luracast/restler, which is used here.

PR for updating the dependency is open ( https://github.com/AOEpeople/TYPO3_Restler/pull/26 ), @tomasnorre and @vdespa are also in the loop.
