### ISSUE TITLE
Calling either "/api_explorer/" or e.g. "api/internal_endpoint/cars/2/" triggers Call to undefined method TYPO3\CMS\Core\Cache\Backend\NullBackend::getCacheDirectory() 

### ISSUE THREAD

**Issue by AMartinNo1** [AOEpeople/TYPO3_Restler#28]
I recently installed both the EXT:restler and EXT:restler_examples. When trying to call either the api_explorer or an endpoint, I receive an exception.

```Uncaught TYPO3 Exception
Call to undefined method TYPO3\CMS\Core\Cache\Backend\NullBackend::getCacheDirectory() 

Error thrown in file ./typo3conf/ext/restler/Classes/System/Restler/Builder.php in line 191.
```

TYPO3 version: 7.6.21
Rester version: 2.0.1
RestlerExamples version: 1.0.0
PHP version: 7.0.22

**Comment by tomasnorre** [comment]
Will have a look, thanks for reporting @AMartinNo1

**Comment by AMartinNo1** [comment]
Thanks, if you need more information don't hesitate to request :)

**Comment by tomasnorre** [comment]
@AMartinNo1 

Did you by any change override the cacheConfiguration for the restler extension? The getCacheDirectory is only implemented in the SimpleFileBackend. 

In the ext_localconf.php we are setting this be default if cache not already set.
`
/**
 * register cache which will be used from restler (to e.g. cache the routes.php)
 */
if (false === isset($GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['tx_restler_cache'])) {
    // only configure cache, when cache is not already configured (e.g. by any other extension which base on this extension)
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations']['tx_restler_cache'] = [
        'backend' => \TYPO3\CMS\Core\Cache\Backend\SimpleFileBackend::class,
        'groups' => ['system']
    ];
}
`

We need to deal with the fact that other caches can be used, but please let me know if you reconfigured the cache for the restler extension.

**Comment by AMartinNo1** [comment]
I would not have done that on purpose. Here is a search result:
![image](https://user-images.githubusercontent.com/5464339/35919165-8f1ce9d8-0c14-11e8-95e7-694e3cdfd8c9.png)

And here's a part of the result when xdebugging the ext_localconf.php file while calling the T3 BE login page.
![image](https://user-images.githubusercontent.com/5464339/35919337-0d28faf6-0c15-11e8-9bd7-b18e520ffdc9.png)

And here's my EXT:restler configuration - the current disabled options were enabled during my several tests either:
![image](https://user-images.githubusercontent.com/5464339/35919496-93c455ec-0c15-11e8-875b-7549d21a696f.png)

**Comment by tomasnorre** [comment]
Hmm. Everything looks fine to me.. Will have to investigate more.. 

Will need to test in a clean environment, cannot promise when I can get back to you.

**Comment by AMartinNo1** [comment]
Alright. Thanks for your quick feedback. No problem.

**Comment by felixsemmler** [comment]
Please check the latest version of [restler](https://extensions.typo3.org/extension/restler) and [restler_examples](https://extensions.typo3.org/extension/restler_examples). We did some changes and update the code for TYPO3V10.
