### ISSUE TITLE
Using url versioning

### ISSUE THREAD

**Issue by MassieurHunter** [AOEpeople/TYPO3_Restler#30]
Hi guys,
I'd like to know if there's a way to use Url Versioning
The api is called on www.example.com/api/v[0-9]/* but the restler class in 
public/typo3conf/ext/restler/vendor/luracast/restler/vendor/Luracast/Restler/Restler.php
search the url version in the first character of the requested path

Typo3 version : 8.7.10
Rester version: 2.0.2
PHP version : 7.1.3

**Comment by tomasnorre** [comment]
Hi @MassieurHunter 

Currently this is unfortunately not possible, but would be cool to have it added. This is something that could be really useful.

**Comment by MassieurHunter** [comment]
Ok, thanks @tomasnorre for your answer ;)
