### ISSUE TITLE
Update luracast/restler fork

### ISSUE THREAD

**Issue by infabo** [AOEpeople/TYPO3_Restler#31]
See https://github.com/Luracast/Restler/issues/591

**Comment by tomasnorre** [comment]
Thanks.. Will look into this.. We are still internally needed this at lower PHP but will check compatibility.

**Comment by tomasnorre** [comment]
We have a 2-0 Branch WIP progress, will include it in there. But will still need to check PHP versions.

**Comment by infabo** [comment]
Thanks! At least this one particular commit did not change anything what would not be backwards compatible. It was just about naming of "Object", which lead to an error in 7.2. So they renamed any occurances to "Obj". :)

Looking forward seeing the updated dependency in WIP 2.0 branch!

**Comment by tomasnorre** [comment]
Are you using the 2.0 Branch/Version, we also have released a 2.x version. @infabo

**Comment by tomasnorre** [comment]
Looks like the new version is compatible with PHP >= 5.3 
https://packagist.org/packages/luracast/restler

**Comment by infabo** [comment]
thanks a lot!

**Comment by tomasnorre** [comment]
@infabo Can you please test branch https://github.com/AOEpeople/TYPO3_Restler/tree/issue/31 and let me know if it works for you. 

Thanks.

**Comment by infabo** [comment]
@tomasnorre Tested it, but it does not work and introduces new errors. I guess your fork uses v3-branch - not master. But just my guess.

**Comment by tomasnorre** [comment]
I merged master into my master, and release a new tag. 

But I'll check.

**Comment by infabo** [comment]
master is not the newest version (I dont even know what master is actually).
The most current branch is v3 -> https://github.com/Luracast/Restler/tree/v3

**Comment by tomasnorre** [comment]
ok.. Then i might have rebase wrongly.. Will check.

**Comment by tomasnorre** [comment]
Fixed, Thanks to @infabo
