### ISSUE TITLE
7 LTS Compatibility

### ISSUE THREAD

**Issue by jmverges** [AOEpeople/TYPO3_Restler#4]
Hi there,
is this extension working properly with 7LTS? I'm getting some exception.
![image](https://cloud.githubusercontent.com/assets/2902073/11763116/6932c8ba-a0fe-11e5-9584-2fc8e351480f.png)

Regards, 
Juan Manuel

**Comment by vdespa** [comment]
Hi Juan Manuel, 

Thanks for letting us know that is not working for you in TYPO3 7.

We have not actively tested it in 7 but we will soon have a look into it and get back to you. 

If it is possible to get it to work with 6.2 and 7, we will fix it.

**Comment by soda-2005** [comment]
The new version 1.2.0 of the restler-Extension now supports TYPO3 7.6 (LTS)
