### ISSUE TITLE
TYPO3 v9 compatibility

### ISSUE THREAD

**Issue by gf-luka** [AOEpeople/TYPO3_Restler#52]
Hello AOEpeople,

I am a little bit confused about the version constraints and the compatibility with TYPO3 v9.

The composer.json implies a compatibility with TYPO3 =< 7.6.0 the ext_emconf.php restricts it to 7.6.0-8.7.99. I don't know, if TYPO3 still checks the ext_emconf.php in composermode.

Are the pull requests about the TYPO3 v9 compatibility stale? Or is this extension already v9 compatible?

Also confusing: the latest release in the TYPO3 extension repository is 2.0.2 but the latest release here on Github is 3.1.3.

It would be nice, if you could bring some light in this. 

Thanks and best,
Gianni

**Comment by StefanMasz** [comment]
Hi Gianni, 
There is a "unstable" V9 branch which is not "released" yet because it breaks the downwards compatibility.
https://github.com/AOEpeople/TYPO3_Restler/tree/TYPO3V9

The tagging in TER should be done by a automatic job. It seems like that one is failing. 
We will have to look into that and think about a "release strategy" for the V9 Version. 

Thanks for your feedback. 
Cheers Stefan

**Comment by derhansen** [comment]
Hi Stefan,

is this https://github.com/AOEpeople/TYPO3_Restler/commits/feature/typo3-v9-master-wip the branch with the v9 compatibility? The one you mentioned is only 6 commits behind master and seems to contain no V9 related changes?

Do you have an idea about, when the V9 version will be released? Is it "just" a matter of testing/user feedback or are there sill some migrations missing? 

Best regards
Torben

**Comment by sven-carstens** [comment]
We are currently using the "typo3-v9-master-wip" in one project in production. But we would welcome more testing before making this branch the new master for everybody.

Travis at least is doing testing for all supported Typo3 versions.

**Comment by tmotyl** [comment]
we're using `"aoe/restler": "dev-feature/typo3-v9-master-wip#5282286"`
on prod since 2 months with a little fix to have it working with TYPO3 running under "subfolder" / "path" and not as root domain

**Comment by sven-carstens** [comment]
@tmotyl Could you send your patch along? Maybe we could integrate it.

**Comment by tmotyl** [comment]
@sven-carstens we're now in the process of profiling as we see mesurable performance drop in restler in v9. I've added first comment in the PR.
Our plan:
- deploy first fixes tomorrow to prod (preventing restler from being called for all requests)
- update restler branch we use to newest commit
- reapply update our path patches to newet restler version
- come back to you with more feedback :)
However if you could take a look at the comment: https://github.com/AOEpeople/TYPO3_Restler/pull/50/files#r374132552 in the meantime, that would be great.

**Comment by infabo** [comment]
Hey,

how can I enable the "api_explorer" in typo3-v9-master-wip again? its enabled in extension-configuration but it just serves an 404. Do I need to configure some route enhancer?

Another question:
Doctrine annotation reader complained about some unknown annotations.
To make it work in v9 I had to add some annotations to doctrine global namespace ignore.

```
\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredName('restler_typo3cache_expires');
\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredName('restler_typo3cache_tags');
\Doctrine\Common\Annotations\AnnotationReader::addGlobalIgnoredName('url');
```

Nobody had this problem?

Is it still way-to-go using the following route enhancer config?

```
routeEnhancers:
    RestlerEnhancer:
        type: Restler
        default: '.json'
```

Thanks! Great work until!

**Comment by tmotyl** [comment]
@infabo we also had to add ignore annotation for url - see the restler slack channel

**Comment by sven-carstens** [comment]
Adding the global ignores seems to be a better way as we can use a class_exists beforehand to keep old Typo3 versions happy.

**Comment by sven-carstens** [comment]
Sitting idle and should be solved.
