### ISSUE TITLE
Requirement "luracast/restler" version with date suffix - no matching package found

### ISSUE THREAD

**Issue by nimayneb** [AOEpeople/TYPO3_Restler#54]
**Usage** (for me)**:**
```composer require aoe/restler ^3.2.0``` (PHP 7.2, TYPO3 8.7)

But with all other versions < 3.2.0 too.

**Problem:**
- Installation request for aoe/restler ^3.2.0 -> satisfiable by aoe/restler[3.2.0].
- aoe/restler 3.2.0 requires luracast/restler 3.0.0.20191001 -> no matching package found.

The GitHub and Packagist releases for package "luracast/restler" shows versions without date suffix ("20191001"). So, the tags are not available (anymore).

**Workaround** (before require "aoe/restler")**:**
```composer require luracast/restler "3.0.0 as 3.0.0.20191001"```

**Comment by sven-carstens** [comment]
There is a separate fork for that:
`
	"repositories": [
		{ "type": "composer", "url": "https://composer.typo3.org/" },
                { "type": "git", "url": "https://github.com/AOEpeople/Restler.git" }
	],
`

**Comment by nimayneb** [comment]
Oh that's all. And it is described in the documentation. Overlooked.
