### ISSUE TITLE
initializeBackendEndUser not compatible with TYPO3 v10.4

### ISSUE THREAD

**Issue by derhansen** [AOEpeople/TYPO3_Restler#56]
Since the extensions is marked as compatible with TYPO3 10.4, there should be a workaround / switch for the new TYPO3 bootstrap.

**References:**
* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.4/Deprecation-85821-BootstrapMethods.html
* https://docs.typo3.org/c/typo3/cms-core/9.5/en-us/Changelog/8.7/Deprecation-80079-DeprecatedBootstraploadExtensionTables.html

For v10.4, the [initializeBackendEndUser](https://github.com/AOEpeople/TYPO3_Restler/blob/master/Classes/System/TYPO3/Loader.php#L89) does not work any more. Code needs to be refactored like:

```
    public function initializeBackendEndUser()
    {
        if(!class_exists('\TYPO3\CMS\Core\Configuration\ExtensionConfiguration')) {
            if ($this->isBackEndUserInitialized === true) {
                return;
            }

            Bootstrap::initializeBackendUser();
            Bootstrap::initializeBackendAuthentication(true);
            Bootstrap::initializeLanguageObject();
        }

        $this->isBackEndUserInitialized = true;
    }
```

Note, the code above is not tested. I have an own `BeUserAuthenticationController` similar to the one in ext:restler, which I had to refactor as shown above.

**Comment by sven-carstens** [comment]
Thanks for the feedback.
As I'm currently not using that functionality that escaped our integration tests.
