### ISSUE TITLE
Fatal error caused by wrong path in Loader

### ISSUE THREAD

**Issue by dwenzel** [AOEpeople/TYPO3_Restler#6]
Calling <hostname>/api_explorer/ results in a fatal error:
`[Sat Mar 12 21:02:50.152534 2016] [:error] [pid 4084] [client 10.0.2.2:56738] PHP Fatal error:  require(): Failed opening required '/var/www/html/typo3conf/ext/restler/Classes/System/TYPO3/../../../../../../../typo3_src/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/typo3conf/ext/restler/Classes/System/TYPO3/Loader.php on line 140
[Sat Mar 12 21:02:50.152975 2016] [:error] [pid 4084] [client 10.0.2.2:56738] PHP Stack trace:
[Sat Mar 12 21:02:50.153372 2016] [:error] [pid 4084] [client 10.0.2.2:56738] PHP   1. {main}() /var/www/html/typo3conf/ext/restler/Scripts/restler_dispatch.php:0
[Sat Mar 12 21:02:50.153741 2016] [:error] [pid 4084] [client 10.0.2.2:56738] PHP   2. Aoe\\Restler\\System\\TYPO3\\Loader->initializeTypo3() /var/www/html/typo3conf/ext/restler/Scripts/restler_dispatch.php:29
`include path should be '__DIR__ . '/../../../../../../typo3_src/vendor/autoload.php''
(6 levels up instead of 7)

- TYPO3 version 7.6.4
- restler version 1.2.13 installed from TER
- restler_examples 0.6.0 installed from TER
- typo3_src is a symlink to the src folder

**Comment by soda-2005** [comment]
Hi,
thanks for your bugfix-report.I fixed the bug in version 1.2.21.

Best regards,
Jürgen Kußmann
