### ISSUE TITLE
Intelephense complains about "undefined types"

### ISSUE THREAD

**Issue by rowild** [AOEpeople/TYPO3_Restler#65]
Any idea why intelephense in VScode complains about what is shown in the screenshot? Whatever result I get on Google, the solution should be to implement the class and the namespace. At least the classes are implemented. 

Any insights?

![Bildschirmfoto 2021-07-16 um 15 45 02](https://user-images.githubusercontent.com/213803/125957785-882d9682-63ed-4752-ab7d-561edc0c098f.png)

**Comment by felixsemmler** [comment]
I'm only using PhpStorm for TYPO3 development, so I can't help you with vscode issues. The files that could not be found in vscode are in the library `luracast/restler`. This is defined as a composer dependency for the `restler` extension. When you setup you TYPO3 and add the `restler` extension to your TYPO3 project setup (root composer.json of your project), `composer install` installs all the dependencies for the extensions into the folder `Packages/Libraries/...`. In case of `luracast/restler` you should find the required sources in the folder `Packages/Libraries/luracast/restler/vendor/Luracast/Restler`.

If this explanation doesn't fix your issue, please provide me more information.
