### ISSUE TITLE
Swagger API overview shows an "INVALID" entry

### ISSUE THREAD

**Issue by rowild** [AOEpeople/TYPO3_Restler#66]
Is this invalid entry to be expected? 

![Bildschirmfoto 2021-07-16 um 15 47 47](https://user-images.githubusercontent.com/213803/125958224-83b77a6a-d046-483c-a89a-76547a2878a6.png)

Clicking on invalid tells me that a "swagger.json" could not be found.

![Bildschirmfoto 2021-07-16 um 16 12 43](https://user-images.githubusercontent.com/213803/125961618-aae0b45e-637c-4341-8a5b-2dbb52ce3b9f.png)

What has to be done?

**Comment by felixsemmler** [comment]
I'm not really deep dived into the swagger topic but swagger try to validate the `swagger.json` from `validator.swagger.io` and seems that you try to use TYPO3 in an docker container/devbox or something else, which is not reachable from the outside of your network. you can ignore this invalid button. Normally the API explorer should not be accessible for production and public reachable websites.
