### ISSUE TITLE
Should new api route show up in swagger overview or not?

### ISSUE THREAD

**Issue by rowild** [AOEpeople/TYPO3_Restler#67]
I am new to all this, and the docu is quite spare. I wonder if a route that I created within my own extension, is nevertheless supposed to show up in the swagger api overview (/api_explorer) – or not?

Thank you!

**Comment by felixsemmler** [comment]
Here you can find an example how to add new controllers and routes to restler:
https://github.com/AOEpeople/TYPO3_RestlerExamples/blob/main/Classes/System/Restler/Configuration.php#L65

After adding some configuration, maybe you should clear all caches to see the new routes in the api_explorer. In a non-production mode the changes should be apply directly, without clearing the cache. You can also have a look at the routing cache folder `typo3temp/Cache/Data/tx_restler_cache` to get more information.
