### ISSUE TITLE
v10.3.2: TYPO3 Exception - $restlerBuilder must not be accessed before initialization

### ISSUE THREAD

**Issue by cschnell** [AOEpeople/TYPO3_Restler#77]
Hi,
with Version 10.3.2 I am experiencing an Exception. The complete error message from my log:
`
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Typed property Aoe\Restler\System\RestlerBuilderAware::$restlerBuilder must not be accessed before initialization | Error thrown in file /var/www/myproject/public/typo3conf/ext/restler/Classes/System/RestlerBuilderAware.php in line 54
`
In Version 10.3.1, everything works fine.

**Comment by TomSchenk** [comment]
Hi @cschnell,
is this still relevant?

**Comment by cschnell** [comment]
Hi @TomSchenk,
fixed with 10.4.2 and all later versions.
Thank you very much.

**Comment by cschnell** [comment]
fixed.
