### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by dogawaf** [AOEpeople/TYPO3_Restler#82]
Hello

Do you plan to upgrade this extension for TYPO3 v12 + PHP 8.2+ ?

**Comment by soda-2005** [comment]
Hi dogawaf,
i guess that unfortunately we can't plan time for this at the moment - sorry.

**Comment by TomSchenk** [comment]
We are currently working on the v12 update incl. PHP 8.2 & 8.3. ETA ~3 months
Feel free to provide a pull request, in the meantime :-)

**Comment by aoekrz** [comment]
@tripulsTPfeffer 
[Here we go - restler v12](https://github.com/AOEpeople/TYPO3_Restler/releases/tag/12.0.2 )

Please let us know if you encounter any issues.
